CREATE OR REPLACE 
FUNCTION checkChanges(lo a_record, ln a_record) RETURNS BOOLEAN AS
$$
DECLARE
     flag  BOOLEAN := false; 
BEGIN
IF lo.A01_N IS NOT NULL AND NULLIF(lo.A01_V,'##NULO##') != NULLIF(ln.A01_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A02_N IS NOT NULL AND NULLIF(lo.A02_V,'##NULO##') != NULLIF(ln.A02_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A03_N IS NOT NULL AND NULLIF(lo.A03_V,'##NULO##') != NULLIF(ln.A03_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A04_N IS NOT NULL AND NULLIF(lo.A04_V,'##NULO##') != NULLIF(ln.A04_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A05_N IS NOT NULL AND NULLIF(lo.A05_V,'##NULO##') != NULLIF(ln.A05_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A06_N IS NOT NULL AND NULLIF(lo.A06_V,'##NULO##') != NULLIF(ln.A06_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A07_N IS NOT NULL AND NULLIF(lo.A07_V,'##NULO##') != NULLIF(ln.A07_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A08_N IS NOT NULL AND NULLIF(lo.A08_V,'##NULO##') != NULLIF(ln.A08_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A09_N IS NOT NULL AND NULLIF(lo.A09_V,'##NULO##') != NULLIF(ln.A09_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A10_N IS NOT NULL AND NULLIF(lo.A10_V,'##NULO##') != NULLIF(ln.A10_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A11_N IS NOT NULL AND NULLIF(lo.A11_V,'##NULO##') != NULLIF(ln.A11_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A12_N IS NOT NULL AND NULLIF(lo.A12_V,'##NULO##') != NULLIF(ln.A12_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A13_N IS NOT NULL AND NULLIF(lo.A13_V,'##NULO##') != NULLIF(ln.A13_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A14_N IS NOT NULL AND NULLIF(lo.A14_V,'##NULO##') != NULLIF(ln.A14_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A15_N IS NOT NULL AND NULLIF(lo.A15_V,'##NULO##') != NULLIF(ln.A15_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A16_N IS NOT NULL AND NULLIF(lo.A16_V,'##NULO##') != NULLIF(ln.A16_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A17_N IS NOT NULL AND NULLIF(lo.A17_V,'##NULO##') != NULLIF(ln.A17_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A18_N IS NOT NULL AND NULLIF(lo.A18_V,'##NULO##') != NULLIF(ln.A18_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A19_N IS NOT NULL AND NULLIF(lo.A19_V,'##NULO##') != NULLIF(ln.A19_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A20_N IS NOT NULL AND NULLIF(lo.A20_V,'##NULO##') != NULLIF(ln.A20_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A21_N IS NOT NULL AND NULLIF(lo.A21_V,'##NULO##') != NULLIF(ln.A21_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A22_N IS NOT NULL AND NULLIF(lo.A22_V,'##NULO##') != NULLIF(ln.A22_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A23_N IS NOT NULL AND NULLIF(lo.A23_V,'##NULO##') != NULLIF(ln.A23_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A24_N IS NOT NULL AND NULLIF(lo.A24_V,'##NULO##') != NULLIF(ln.A24_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A25_N IS NOT NULL AND NULLIF(lo.A25_V,'##NULO##') != NULLIF(ln.A25_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A26_N IS NOT NULL AND NULLIF(lo.A26_V,'##NULO##') != NULLIF(ln.A26_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A27_N IS NOT NULL AND NULLIF(lo.A27_V,'##NULO##') != NULLIF(ln.A27_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A28_N IS NOT NULL AND NULLIF(lo.A28_V,'##NULO##') != NULLIF(ln.A28_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A29_N IS NOT NULL AND NULLIF(lo.A29_V,'##NULO##') != NULLIF(ln.A29_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A30_N IS NOT NULL AND NULLIF(lo.A30_V,'##NULO##') != NULLIF(ln.A30_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A31_N IS NOT NULL AND NULLIF(lo.A31_V,'##NULO##') != NULLIF(ln.A31_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A32_N IS NOT NULL AND NULLIF(lo.A32_V,'##NULO##') != NULLIF(ln.A32_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A33_N IS NOT NULL AND NULLIF(lo.A33_V,'##NULO##') != NULLIF(ln.A33_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A34_N IS NOT NULL AND NULLIF(lo.A34_V,'##NULO##') != NULLIF(ln.A34_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A35_N IS NOT NULL AND NULLIF(lo.A35_V,'##NULO##') != NULLIF(ln.A35_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A36_N IS NOT NULL AND NULLIF(lo.A36_V,'##NULO##') != NULLIF(ln.A36_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A37_N IS NOT NULL AND NULLIF(lo.A37_V,'##NULO##') != NULLIF(ln.A37_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A38_N IS NOT NULL AND NULLIF(lo.A38_V,'##NULO##') != NULLIF(ln.A38_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A39_N IS NOT NULL AND NULLIF(lo.A39_V,'##NULO##') != NULLIF(ln.A39_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A40_N IS NOT NULL AND NULLIF(lo.A40_V,'##NULO##') != NULLIF(ln.A40_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A41_N IS NOT NULL AND NULLIF(lo.A41_V,'##NULO##') != NULLIF(ln.A41_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A42_N IS NOT NULL AND NULLIF(lo.A42_V,'##NULO##') != NULLIF(ln.A42_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A43_N IS NOT NULL AND NULLIF(lo.A43_V,'##NULO##') != NULLIF(ln.A43_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A44_N IS NOT NULL AND NULLIF(lo.A44_V,'##NULO##') != NULLIF(ln.A44_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A45_N IS NOT NULL AND NULLIF(lo.A45_V,'##NULO##') != NULLIF(ln.A45_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A46_N IS NOT NULL AND NULLIF(lo.A46_V,'##NULO##') != NULLIF(ln.A46_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A47_N IS NOT NULL AND NULLIF(lo.A47_V,'##NULO##') != NULLIF(ln.A47_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A48_N IS NOT NULL AND NULLIF(lo.A48_V,'##NULO##') != NULLIF(ln.A48_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A49_N IS NOT NULL AND NULLIF(lo.A49_V,'##NULO##') != NULLIF(ln.A49_V,'##NULO##') THEN 
flag := true;
ELSIF lo.A50_N IS NOT NULL AND NULLIF(lo.A50_V,'##NULO##') != NULLIF(ln.A50_V,'##NULO##') THEN 
flag := true;
END IF;
	RETURN flag;
END;
$$ LANGUAGE PLPGSQL;
